spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jackson:
    propertyNamingStrategy: LOWER_CAMEL_CASE
  data:
    jpa:
      repositories: enabled=false
      
      
user-defined:
  allowed-origin: https://listifye.herokuapp.com/