spring:
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driverClassName: com.mysql.jdbc.Driver
  data:
    jpa:
      repositories: enabled=false
  jackson:
      propertyNamingStrategy: LOWER_CAMEL_CASE
    
user-defined:
  allowed-origin: localhost:8080/
  
logging:
  level:
    root: debug