spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jackson:
    propertyNamingStrategy: LOWER_CAMEL_CASE
      
      
user-defined:
  allowed-origin: localhost:8080/
  
logging:
  level:
    root: debug